baseURL = 'https://tky116.github.io/'
languageCode = 'ja-jp'
title = 'tky'
timeZone = "Asia/Tokyo"

# 言語設定
defaultContentLanguage = 'ja'
hasCJKLanguage = true

# その他の設定
enableEmoji = true

# モジュール設定を使用
[module]
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5"
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify"
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-reveal"
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind"

# セキュリティ設定に環境変数アクセス許可を追加
[security.funcs]
  getenv = ['^HUGO_', '^CI$', '^WC_']

# Markdownレンダリング設定
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# サイトマップ設定
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

# メニュー設定
[menu]
  [[menu.main]]
    name = "Home"
    url = "#about"
    weight = 10
  [[menu.main]]
    name = "Achievements"
    url = "#achievements"
    weight = 30
  [[menu.main]]
    name = "Projects"
    url = "#projects"
    weight = 40
  [[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 50

# パラメータ設定
[params]
  # SEO対策用メタデータ
  description = "tky116のポートフォリオサイト"
  author = "Takuya Okamoto"
  
  # SNSリンク設定
  [params.social]
    github = "tky116"
    twitter = "dot_asterisk"